Fix and update celery init scripts

diff --git a/templates/celery-init.erb b/templates/celery-init.erb
--- a/templates/celery-init.erb
+++ b/templates/celery-init.erb
@@ -6,41 +6,70 @@
 # :Usage: /etc/init.d/celeryd {start|stop|force-reload|restart|try-restart|status}
 # :Configuration file: /etc/default/celeryd
 #
+# See http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html#generic-init-scripts
 
-# To configure celeryd you probably need to tell it where to chdir.
+
 ### BEGIN INIT INFO
 # Provides:          celeryd
 # Required-Start:    $network $local_fs $remote_fs
 # Required-Stop:     $network $local_fs $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: celeryd worker daemon
+# Short-Description: celery task worker daemon
 ### END INIT INFO
+#
+#
+# To implement separate init scripts, do NOT copy this script.  Instead,
+# symlink it.  I.e., if my new application, "little-worker" needs an init, I
+# should just use:
+#
+#   ln -s /etc/init.d/celeryd /etc/init.d/little-worker
+#
+# You can then configure this by manipulating /etc/default/little-worker.
+#
+# If you want to have separate LSB headers in each script you can source this
+# script instead of symlinking:
+#   # ...
+#   ### END INIT INFO
+#   source /etc/init.d/celeryd
+#
+# Setting `SCRIPT_NAME` here allows you to symlink/source this init script,
+# making it easy to run multiple processes on the system.
+SCRIPT_NAME="$(basename $0)"
 
-# Cannot use set -e/bash -e since the kill -0 command will abort
-# abnormally in the absence of a valid process ID.
-#set -e
-
-DEFAULT_PID_FILE="/var/run/celeryd@%n.pid"
-DEFAULT_LOG_FILE="/var/log/celeryd@%n.log"
+DEFAULT_PID_FILE="/var/run/celery/${SCRIPT_NAME}/%n.pid"
+DEFAULT_LOG_FILE="/var/log/celery/${SCRIPT_NAME}/%n.log"
 DEFAULT_LOG_LEVEL="INFO"
 DEFAULT_NODES="celery"
-DEFAULT_CELERYD="-m celery.bin.celeryd_detach"
+DEFAULT_CELERYD="-m celery worker --detach"
 
-# /etc/init.d/celeryd: start and stop the celery task worker daemon.
-
-CELERY_DEFAULTS=${CELERY_DEFAULTS:-"/etc/default/celeryd"}
+CELERY_DEFAULTS=${CELERY_DEFAULTS:-"/etc/default/${SCRIPT_NAME}"}
 
 test -f "$CELERY_DEFAULTS" && . "$CELERY_DEFAULTS"
-if [ -f "/etc/default/celeryd" ]; then
-    . /etc/default/celeryd
+
+# Sets --app argument for CELERY_BIN
+CELERY_APP_ARG=""
+if [ ! -z "$CELERY_APP" ]; then
+    CELERY_APP_ARG="--app=$CELERY_APP"
 fi
 
-CELERYD_PID_FILE=${CELERYD_PID_FILE:-${CELERYD_PIDFILE:-$DEFAULT_PID_FILE}}
-CELERYD_LOG_FILE=${CELERYD_LOG_FILE:-${CELERYD_LOGFILE:-$DEFAULT_LOG_FILE}}
+
+# Set CELERY_CREATE_DIRS to always create log/pid dirs.
+CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS:-0}
+CELERY_CREATE_RUNDIR=$CELERY_CREATE_DIRS
+CELERY_CREATE_LOGDIR=$CELERY_CREATE_DIRS
+if [ -z "$CELERYD_PID_FILE" ]; then
+    CELERYD_PID_FILE="$DEFAULT_PID_FILE"
+    CELERY_CREATE_RUNDIR=1
+fi
+if [ -z "$CELERYD_LOG_FILE" ]; then
+    CELERYD_LOG_FILE="$DEFAULT_LOG_FILE"
+    CELERY_CREATE_LOGDIR=1
+fi
+
 CELERYD_LOG_LEVEL=${CELERYD_LOG_LEVEL:-${CELERYD_LOGLEVEL:-$DEFAULT_LOG_LEVEL}}
-CELERYD_MULTI=${CELERYD_MULTI:-"celery multi"}
-CELERYD=${CELERYD:-$DEFAULT_CELERYD}
+CELERY_BIN=${CELERY_BIN:-"celery"}
+CELERYD_MULTI=${CELERYD_MULTI:-"$CELERY_BIN multi"}
 CELERYD_NODES=${CELERYD_NODES:-$DEFAULT_NODES}
 
 export CELERY_LOADER
@@ -48,6 +77,9 @@ export CELERY_LOADER
 if [ -n "$2" ]; then
     CELERYD_OPTS="$CELERYD_OPTS $2"
 fi
+
+CELERYD_LOG_DIR=`dirname $CELERYD_LOG_FILE`
+CELERYD_PID_DIR=`dirname $CELERYD_PID_FILE`
 
 # Extra start-stop-daemon options, like user/group.
 if [ -n "$CELERYD_USER" ]; then
@@ -58,31 +90,114 @@ if [ -n "$CELERYD_GROUP" ]; then
 fi
 
 if [ -n "$CELERYD_CHDIR" ]; then
-    DAEMON_OPTS="$DAEMON_OPTS --workdir=\"$CELERYD_CHDIR\""
+    DAEMON_OPTS="$DAEMON_OPTS --workdir=$CELERYD_CHDIR"
 fi
 
 
 check_dev_null() {
     if [ ! -c /dev/null ]; then
         echo "/dev/null is not a character device!"
-        exit 1
+        exit 75  # EX_TEMPFAIL
     fi
+}
+
+
+maybe_die() {
+    if [ $? -ne 0 ]; then
+        echo "Exiting: $* (errno $?)"
+        exit 77  # EX_NOPERM
+    fi
+}
+
+create_default_dir() {
+    if [ ! -d "$1" ]; then
+        echo "- Creating default directory: '$1'"
+        mkdir -p "$1"
+        maybe_die "Couldn't create directory $1"
+        echo "- Changing permissions of '$1' to 02755"
+        chmod 02755 "$1"
+        maybe_die "Couldn't change permissions for $1"
+        if [ -n "$CELERYD_USER" ]; then
+            echo "- Changing owner of '$1' to '$CELERYD_USER'"
+            chown "$CELERYD_USER" "$1"
+            maybe_die "Couldn't change owner of $1"
+        fi
+        if [ -n "$CELERYD_GROUP" ]; then
+            echo "- Changing group of '$1' to '$CELERYD_GROUP'"
+            chgrp "$CELERYD_GROUP" "$1"
+            maybe_die "Couldn't change group of $1"
+        fi
+    fi
+}
+
+
+check_paths() {
+    if [ $CELERY_CREATE_LOGDIR -eq 1 ]; then
+        create_default_dir "$CELERYD_LOG_DIR"
+    fi
+    if [ $CELERY_CREATE_RUNDIR -eq 1 ]; then
+        create_default_dir "$CELERYD_PID_DIR"
+    fi
+}
+
+create_paths() {
+    create_default_dir "$CELERYD_LOG_DIR"
+    create_default_dir "$CELERYD_PID_DIR"
 }
 
 export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
-stop_workers () {
-    sudo $CELERYD_MULTI stop $CELERYD_NODES --pidfile="$CELERYD_PID_FILE"
-    #sudo -u <%= @broker_user %> $CELERYD_MULTI stop $CELERYD_NODES --pidfile="$CELERYD_PID_FILE"
+
+_get_pid_files() {
+    [ ! -d "$CELERYD_PID_DIR" ] && return
+    echo `ls -1 "$CELERYD_PID_DIR"/*.pid 2> /dev/null`
+}
+
+_get_pids() {
+    local pid_files=
+    pid_files=`_get_pid_files`
+    [ -z "$pid_files" ] && echo "${SCRIPT_NAME} is stopped" && exit 1
+
+    for pid_file in $pid_files; do
+        local pid=`cat "$pid_file"`
+        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
+        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
+            echo "bad pid file ($pid_file)"
+            one_failed=true
+        else
+            echo "$pid"
+        fi
+    done
+}
+
+_get_worker_pids() {
+    local pids=
+    pids=`_get_pids`
+    local worker_pids=
+    for pid in $pids; do
+        worker_pids=`ps h --ppid $pid -o pid`
+        [ "$worker_pids" ] && echo "$worker_pids" || one_failed=true
+    done
 }
 
 start_workers () {
-    sudo $CELERYD_MULTI start $CELERYD_NODES $DAEMON_OPTS        \
+    if [ ! -z "$CELERYD_ULIMIT" ]; then
+        ulimit $CELERYD_ULIMIT
+    fi
+    sudo $CELERYD_MULTI $* start $CELERYD_NODES $DAEMON_OPTS     \
                          --pidfile="$CELERYD_PID_FILE"      \
                          --logfile="$CELERYD_LOG_FILE"      \
                          --loglevel="$CELERYD_LOG_LEVEL"    \
-                         --cmd="$CELERYD"                   \
+                         $CELERY_APP_ARG                    \
                          $CELERYD_OPTS
+}
+
+dryrun () {
+    (C_FAKEFORK=1 start_workers --verbose)
+}
+
+stop_workers () {
+    sudo $CELERYD_MULTI stopwait $CELERYD_NODES --pidfile="$CELERYD_PID_FILE"
 }
 
 restart_workers () {
@@ -90,18 +205,71 @@ restart_workers () {
                            --pidfile="$CELERYD_PID_FILE"    \
                            --logfile="$CELERYD_LOG_FILE"    \
                            --loglevel="$CELERYD_LOG_LEVEL"  \
-                           --cmd="$CELERYD"                 \
+                           $CELERY_APP_ARG                  \
                            $CELERYD_OPTS
+}
+
+kill_workers() {
+    sudo $CELERYD_MULTI kill $CELERYD_NODES --pidfile="$CELERYD_PID_FILE"
+}
+
+restart_workers_graceful () {
+    local worker_pids=
+    worker_pids=`_get_worker_pids`
+    [ "$one_failed" ] && exit 1
+
+    for worker_pid in $worker_pids; do
+        local failed=
+        sudo -u $CELERYD_USER kill -HUP $worker_pid 2> /dev/null || failed=true
+        if [ "$failed" ]; then
+            echo "${SCRIPT_NAME} worker (pid $worker_pid) could not be restarted"
+            one_failed=true
+        else
+            echo "${SCRIPT_NAME} worker (pid $worker_pid) received SIGHUP"
+        fi
+    done
+
+    [ "$one_failed" ] && exit 1 || exit 0
+}
+
+
+check_status () {
+    local pid_files=
+    pid_files=`_get_pid_files`
+    [ -z "$pid_files" ] && echo "${SCRIPT_NAME} not running (no pidfile)" && exit 1
+
+    local one_failed=
+    for pid_file in $pid_files; do
+        local node=`basename "$pid_file" .pid`
+        local pid=`cat "$pid_file"`
+        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
+        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
+            echo "bad pid file ($pid_file)"
+        else
+            local failed=
+            sudo -u $CELERYD_USER kill -0 $pid 2> /dev/null || failed=true
+            if [ "$failed" ]; then
+                echo "${SCRIPT_NAME} (node $node) (pid $pid) is stopped, but pid file exists!"
+                one_failed=true
+            else
+                echo "${SCRIPT_NAME} (node $node) (pid $pid) is running..."
+            fi
+        fi
+    done
+
+    [ "$one_failed" ] && exit 1 || exit 0
 }
 
 case "$1" in
     start)
         check_dev_null
+        check_paths
         start_workers
     ;;
 
     stop)
         check_dev_null
+        check_paths
         stop_workers
     ;;
 
@@ -110,24 +278,49 @@ case "$1" in
     ;;
 
     status)
-        OLDPWD="`/bin/pwd`"
-        cd "/var/celery" && celery status
-        cd "${OLDPWD}"
+        check_status
     ;;
 
     restart)
         check_dev_null
+        check_paths
         restart_workers
+    ;;
+
+    graceful)
+        check_dev_null
+        restart_workers_graceful
+    ;;
+
+    kill)
+        check_dev_null
+        kill_workers
+    ;;
+
+    dryrun)
+        check_dev_null
+        dryrun
     ;;
 
     try-restart)
         check_dev_null
+        check_paths
         restart_workers
     ;;
 
+    create-paths)
+        check_dev_null
+        create_paths
+    ;;
+
+    check-paths)
+        check_dev_null
+        check_paths
+    ;;
+
     *)
-        echo "Usage: /etc/init.d/celeryd {start|stop|restart|try-restart|kill}"
-        exit 64
+        echo "Usage: /etc/init.d/${SCRIPT_NAME} {start|stop|restart|graceful|kill|dryrun|create-paths}"
+        exit 64  # EX_USAGE
     ;;
 esac
 
